python3 train.py \
-n C-VTON-MPV \
--dataset mpv \
--batch_size 16 \
--add_vgg_loss \
--lambda_vgg 10 \
--add_d_loss \
--add_cd_loss \
--add_pd_loss \
--no_labelmix \
--img_size 256 \
--segmentation densepose \
--transform_cloth \
--bpgm_id 256_26_3_mpv_192 \
